### Numpy :
1. n-dimensional array
2. working with numerics

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5]

In [3]:
arr1 = np.array(list1)

In [4]:
print(type(list1),type(arr1))

<class 'list'> <class 'numpy.ndarray'>


In [5]:
#Accesing elements
list1[2]

3

In [6]:
arr1[2]

3

### 3 benefits of numpy array over a python list
1. less memory
2. Fast
3. convinient

In [7]:
list1

[1, 2, 3, 4, 5]

In [8]:
arr1

array([1, 2, 3, 4, 5])

In [9]:
from sys import getsizeof

In [10]:
getsizeof(list1[0]) * len(list1)

140

In [11]:
arr1.size

5

In [12]:
arr1.itemsize * arr1.size

20

In [13]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
list3

[7, 9, 11, 13, 15]

In [14]:
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1 + arr2

array([ 7,  9, 11, 13, 15])

### Attributes or Properties
1. ndim
2. itemsize
3. dtype
4. size
5. shape
6. flat

In [15]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
#ndim ==> n dimension
arr1.ndim

1

In [17]:
#dtype ==> data type ==> int32,float64,complex
arr1.dtype

dtype('int32')

In [18]:
arr1.shape

(5,)

In [19]:
list3 = [[1,2,3],
        [4,5,6],
        [7,8,9]]
arr3 = np.array(list3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr3.ndim

2

In [21]:
arr3.shape

(3, 3)

In [23]:
#flat ==> flattens your array
np.array(arr3.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr3.itemsize

4

### Functions
1. zeros()
2. ones()
3. full()
4. arange()
5. reshape()
6. ravel()

In [25]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [27]:
np.full((2,2),12)

array([[12, 12],
       [12, 12]])

In [29]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [34]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.array(arr3.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Maths operations

In [41]:
arr1

array([1, 2, 3, 4, 5])

In [42]:
arr2

array([ 6,  7,  8,  9, 10])

In [43]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
#min() and max()
print(arr1.min())
print(arr1.max())
print(arr3.min())
print(arr3.max())

1
5
1
9


In [49]:
#sum()
print(arr3.sum())
print(arr3.sum(axis = 1))#row
print(arr3.sum(axis = 0))#coumns

45
[ 6 15 24]
[12 15 18]


In [50]:
arr3.mean()

5.0

In [52]:
np.median(arr3)

5.0

In [53]:
np.std(arr3)

2.581988897471611

In [54]:
np.sqrt(arr3)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [55]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)


In [56]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [58]:
#matrix multiplication
a1.dot(a2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [59]:
#Transpose a matrix
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])